name: cloud_walk_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  easy_localization: ^3.0.4
  core:
    git:
      url: https://github.com/leobidoous/core.git
      branch: main

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .environment/
    - translations/
