name: cloud_walk_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    git:
      url: https://github.com/leobidoous/core.git
      # tag: 1.0.0
      branch: main

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true

  assets:
    - .environment/
